// Mocks generated by Mockito 5.4.5 from annotations
// in adair_flutter_lib/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:io' as _i19;
import 'dart:ui' as _i3;

import 'package:adair_flutter_lib/app_config.dart' as _i10;
import 'package:adair_flutter_lib/managers/properties_manager.dart' as _i22;
import 'package:adair_flutter_lib/managers/subscription_manager.dart' as _i24;
import 'package:adair_flutter_lib/managers/time_manager.dart' as _i9;
import 'package:adair_flutter_lib/utils/string.dart' as _i11;
import 'package:adair_flutter_lib/wrappers/crashlytics_wrapper.dart' as _i13;
import 'package:adair_flutter_lib/wrappers/io_wrapper.dart' as _i18;
import 'package:adair_flutter_lib/wrappers/native_time_zone_wrapper.dart'
    as _i20;
import 'package:adair_flutter_lib/wrappers/purchases_wrapper.dart' as _i23;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/services.dart' as _i21;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:purchases_flutter/models/entitlement_info_wrapper.dart' as _i6;
import 'package:purchases_flutter/models/entitlement_infos_wrapper.dart' as _i4;
import 'package:purchases_flutter/models/store.dart' as _i16;
import 'package:purchases_flutter/models/store_transaction.dart' as _i15;
import 'package:purchases_flutter/models/verification_result.dart' as _i17;
import 'package:purchases_flutter/object_wrappers.dart' as _i5;
import 'package:purchases_flutter/purchases_flutter.dart' as _i7;
import 'package:timezone/timezone.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIconData_0 extends _i1.SmartFake implements _i2.IconData {
  _FakeIconData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeColor_1 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEntitlementInfos_2 extends _i1.SmartFake
    implements _i4.EntitlementInfos {
  _FakeEntitlementInfos_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CustomerInfoCopyWith_3<$Res> extends _i1.SmartFake
    implements _i5.$CustomerInfoCopyWith<$Res> {
  _Fake$CustomerInfoCopyWith_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EntitlementInfoCopyWith_4<$Res> extends _i1.SmartFake
    implements _i6.$EntitlementInfoCopyWith<$Res> {
  _Fake$EntitlementInfoCopyWith_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EntitlementInfosCopyWith_5<$Res> extends _i1.SmartFake
    implements _i4.$EntitlementInfosCopyWith<$Res> {
  _Fake$EntitlementInfosCopyWith_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomerInfo_6 extends _i1.SmartFake implements _i5.CustomerInfo {
  _FakeCustomerInfo_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OfferingCopyWith_7<$Res> extends _i1.SmartFake
    implements _i5.$OfferingCopyWith<$Res> {
  _Fake$OfferingCopyWith_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OfferingsCopyWith_8<$Res> extends _i1.SmartFake
    implements _i5.$OfferingsCopyWith<$Res> {
  _Fake$OfferingsCopyWith_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoreProduct_9 extends _i1.SmartFake implements _i5.StoreProduct {
  _FakeStoreProduct_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePresentedOfferingContext_10 extends _i1.SmartFake
    implements _i5.PresentedOfferingContext {
  _FakePresentedOfferingContext_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PackageCopyWith_11<$Res> extends _i1.SmartFake
    implements _i5.$PackageCopyWith<$Res> {
  _Fake$PackageCopyWith_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfferings_12 extends _i1.SmartFake implements _i5.Offerings {
  _FakeOfferings_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogInResult_13 extends _i1.SmartFake implements _i7.LogInResult {
  _FakeLogInResult_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StoreProductCopyWith_14<$Res> extends _i1.SmartFake
    implements _i5.$StoreProductCopyWith<$Res> {
  _Fake$StoreProductCopyWith_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTZDateTime_15 extends _i1.SmartFake implements _i8.TZDateTime {
  _FakeTZDateTime_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeZoneLocation_16 extends _i1.SmartFake
    implements _i9.TimeZoneLocation {
  _FakeTimeZoneLocation_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeOfDay_17 extends _i1.SmartFake implements _i2.TimeOfDay {
  _FakeTimeOfDay_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfig extends _i1.Mock implements _i10.AppConfig {
  MockAppConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.StringCallback get appName =>
      (super.noSuchMethod(
            Invocation.getter(#appName),
            returnValue:
                (_i2.BuildContext __p0) =>
                    _i12.dummyValue<String>(this, Invocation.getter(#appName)),
          )
          as _i11.StringCallback);

  @override
  set appName(_i11.StringCallback? _appName) => super.noSuchMethod(
    Invocation.setter(#appName, _appName),
    returnValueForMissingStub: null,
  );

  @override
  _i2.IconData get appIcon =>
      (super.noSuchMethod(
            Invocation.getter(#appIcon),
            returnValue: _FakeIconData_0(this, Invocation.getter(#appIcon)),
          )
          as _i2.IconData);

  @override
  set appIcon(_i2.IconData? _appIcon) => super.noSuchMethod(
    Invocation.setter(#appIcon, _appIcon),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Color get colorAppTheme =>
      (super.noSuchMethod(
            Invocation.getter(#colorAppTheme),
            returnValue: _FakeColor_1(this, Invocation.getter(#colorAppTheme)),
          )
          as _i3.Color);

  @override
  set colorAppTheme(_i3.Color? _colorAppTheme) => super.noSuchMethod(
    Invocation.setter(#colorAppTheme, _colorAppTheme),
    returnValueForMissingStub: null,
  );

  @override
  void init({
    required _i11.StringCallback? appName,
    _i2.IconData? appIcon,
    _i3.Color? colorAppTheme,
  }) => super.noSuchMethod(
    Invocation.method(#init, [], {
      #appName: appName,
      #appIcon: appIcon,
      #colorAppTheme: colorAppTheme,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CrashlyticsWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsWrapper extends _i1.Mock
    implements _i13.CrashlyticsWrapper {
  MockCrashlyticsWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<void> log(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#log, [message]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> recordError(
    String? message,
    StackTrace? stack,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordError, [message, stack, reason]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setUserId(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [identifier]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [CustomerInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerInfo extends _i1.Mock implements _i5.CustomerInfo {
  MockCustomerInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EntitlementInfos get entitlements =>
      (super.noSuchMethod(
            Invocation.getter(#entitlements),
            returnValue: _FakeEntitlementInfos_2(
              this,
              Invocation.getter(#entitlements),
            ),
          )
          as _i4.EntitlementInfos);

  @override
  Map<String, String?> get allPurchaseDates =>
      (super.noSuchMethod(
            Invocation.getter(#allPurchaseDates),
            returnValue: <String, String?>{},
          )
          as Map<String, String?>);

  @override
  List<String> get activeSubscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get allPurchasedProductIdentifiers =>
      (super.noSuchMethod(
            Invocation.getter(#allPurchasedProductIdentifiers),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i15.StoreTransaction> get nonSubscriptionTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#nonSubscriptionTransactions),
            returnValue: <_i15.StoreTransaction>[],
          )
          as List<_i15.StoreTransaction>);

  @override
  String get firstSeen =>
      (super.noSuchMethod(
            Invocation.getter(#firstSeen),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#firstSeen),
            ),
          )
          as String);

  @override
  String get originalAppUserId =>
      (super.noSuchMethod(
            Invocation.getter(#originalAppUserId),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#originalAppUserId),
            ),
          )
          as String);

  @override
  Map<String, String?> get allExpirationDates =>
      (super.noSuchMethod(
            Invocation.getter(#allExpirationDates),
            returnValue: <String, String?>{},
          )
          as Map<String, String?>);

  @override
  String get requestDate =>
      (super.noSuchMethod(
            Invocation.getter(#requestDate),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#requestDate),
            ),
          )
          as String);

  @override
  _i5.$CustomerInfoCopyWith<_i5.CustomerInfo> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$CustomerInfoCopyWith_3<_i5.CustomerInfo>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$CustomerInfoCopyWith<_i5.CustomerInfo>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [EntitlementInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfo extends _i1.Mock implements _i6.EntitlementInfo {
  MockEntitlementInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  bool get isActive =>
      (super.noSuchMethod(Invocation.getter(#isActive), returnValue: false)
          as bool);

  @override
  bool get willRenew =>
      (super.noSuchMethod(Invocation.getter(#willRenew), returnValue: false)
          as bool);

  @override
  String get latestPurchaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#latestPurchaseDate),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#latestPurchaseDate),
            ),
          )
          as String);

  @override
  String get originalPurchaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#originalPurchaseDate),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#originalPurchaseDate),
            ),
          )
          as String);

  @override
  String get productIdentifier =>
      (super.noSuchMethod(
            Invocation.getter(#productIdentifier),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#productIdentifier),
            ),
          )
          as String);

  @override
  bool get isSandbox =>
      (super.noSuchMethod(Invocation.getter(#isSandbox), returnValue: false)
          as bool);

  @override
  _i6.OwnershipType get ownershipType =>
      (super.noSuchMethod(
            Invocation.getter(#ownershipType),
            returnValue: _i6.OwnershipType.purchased,
          )
          as _i6.OwnershipType);

  @override
  _i16.Store get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _i16.Store.appStore,
          )
          as _i16.Store);

  @override
  _i6.PeriodType get periodType =>
      (super.noSuchMethod(
            Invocation.getter(#periodType),
            returnValue: _i6.PeriodType.intro,
          )
          as _i6.PeriodType);

  @override
  _i17.VerificationResult get verification =>
      (super.noSuchMethod(
            Invocation.getter(#verification),
            returnValue: _i17.VerificationResult.notRequested,
          )
          as _i17.VerificationResult);

  @override
  _i6.$EntitlementInfoCopyWith<_i6.EntitlementInfo> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$EntitlementInfoCopyWith_4<_i6.EntitlementInfo>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i6.$EntitlementInfoCopyWith<_i6.EntitlementInfo>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [EntitlementInfos].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfos extends _i1.Mock implements _i4.EntitlementInfos {
  MockEntitlementInfos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i6.EntitlementInfo> get all =>
      (super.noSuchMethod(
            Invocation.getter(#all),
            returnValue: <String, _i6.EntitlementInfo>{},
          )
          as Map<String, _i6.EntitlementInfo>);

  @override
  Map<String, _i6.EntitlementInfo> get active =>
      (super.noSuchMethod(
            Invocation.getter(#active),
            returnValue: <String, _i6.EntitlementInfo>{},
          )
          as Map<String, _i6.EntitlementInfo>);

  @override
  _i17.VerificationResult get verification =>
      (super.noSuchMethod(
            Invocation.getter(#verification),
            returnValue: _i17.VerificationResult.notRequested,
          )
          as _i17.VerificationResult);

  @override
  _i4.$EntitlementInfosCopyWith<_i4.EntitlementInfos> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$EntitlementInfosCopyWith_5<_i4.EntitlementInfos>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i4.$EntitlementInfosCopyWith<_i4.EntitlementInfos>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [IoWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIoWrapper extends _i1.Mock implements _i18.IoWrapper {
  MockIoWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAndroid =>
      (super.noSuchMethod(Invocation.getter(#isAndroid), returnValue: false)
          as bool);

  @override
  bool get isIOS =>
      (super.noSuchMethod(Invocation.getter(#isIOS), returnValue: false)
          as bool);

  @override
  _i14.Future<List<_i19.InternetAddress>> lookup(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#lookup, [host]),
            returnValue: _i14.Future<List<_i19.InternetAddress>>.value(
              <_i19.InternetAddress>[],
            ),
          )
          as _i14.Future<List<_i19.InternetAddress>>);
}

/// A class which mocks [LogInResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogInResult extends _i1.Mock implements _i7.LogInResult {
  MockLogInResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get created =>
      (super.noSuchMethod(Invocation.getter(#created), returnValue: false)
          as bool);

  @override
  _i5.CustomerInfo get customerInfo =>
      (super.noSuchMethod(
            Invocation.getter(#customerInfo),
            returnValue: _FakeCustomerInfo_6(
              this,
              Invocation.getter(#customerInfo),
            ),
          )
          as _i5.CustomerInfo);
}

/// A class which mocks [NativeTimeZoneWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNativeTimeZoneWrapper extends _i1.Mock
    implements _i20.NativeTimeZoneWrapper {
  MockNativeTimeZoneWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<String>> getAvailableTimeZones() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableTimeZones, []),
            returnValue: _i14.Future<List<String>>.value(<String>[]),
          )
          as _i14.Future<List<String>>);

  @override
  _i14.Future<String> getLocalTimeZone() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalTimeZone, []),
            returnValue: _i14.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getLocalTimeZone, []),
              ),
            ),
          )
          as _i14.Future<String>);
}

/// A class which mocks [Offering].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffering extends _i1.Mock implements _i5.Offering {
  MockOffering() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  String get serverDescription =>
      (super.noSuchMethod(
            Invocation.getter(#serverDescription),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#serverDescription),
            ),
          )
          as String);

  @override
  Map<String, Object> get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: <String, Object>{},
          )
          as Map<String, Object>);

  @override
  List<_i5.Package> get availablePackages =>
      (super.noSuchMethod(
            Invocation.getter(#availablePackages),
            returnValue: <_i5.Package>[],
          )
          as List<_i5.Package>);

  @override
  _i5.$OfferingCopyWith<_i5.Offering> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$OfferingCopyWith_7<_i5.Offering>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$OfferingCopyWith<_i5.Offering>);

  @override
  _i5.Package? getPackage(String? identifier) =>
      (super.noSuchMethod(Invocation.method(#getPackage, [identifier]))
          as _i5.Package?);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [Offerings].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfferings extends _i1.Mock implements _i5.Offerings {
  MockOfferings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i5.Offering> get all =>
      (super.noSuchMethod(
            Invocation.getter(#all),
            returnValue: <String, _i5.Offering>{},
          )
          as Map<String, _i5.Offering>);

  @override
  _i5.$OfferingsCopyWith<_i5.Offerings> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$OfferingsCopyWith_8<_i5.Offerings>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$OfferingsCopyWith<_i5.Offerings>);

  @override
  _i5.Offering? getOffering(String? identifier) =>
      (super.noSuchMethod(Invocation.method(#getOffering, [identifier]))
          as _i5.Offering?);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [Package].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackage extends _i1.Mock implements _i5.Package {
  MockPackage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  _i5.PackageType get packageType =>
      (super.noSuchMethod(
            Invocation.getter(#packageType),
            returnValue: _i5.PackageType.unknown,
          )
          as _i5.PackageType);

  @override
  _i5.StoreProduct get storeProduct =>
      (super.noSuchMethod(
            Invocation.getter(#storeProduct),
            returnValue: _FakeStoreProduct_9(
              this,
              Invocation.getter(#storeProduct),
            ),
          )
          as _i5.StoreProduct);

  @override
  _i5.PresentedOfferingContext get presentedOfferingContext =>
      (super.noSuchMethod(
            Invocation.getter(#presentedOfferingContext),
            returnValue: _FakePresentedOfferingContext_10(
              this,
              Invocation.getter(#presentedOfferingContext),
            ),
          )
          as _i5.PresentedOfferingContext);

  @override
  _i5.$PackageCopyWith<_i5.Package> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$PackageCopyWith_11<_i5.Package>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$PackageCopyWith<_i5.Package>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [PlatformException].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformException extends _i1.Mock implements _i21.PlatformException {
  MockPlatformException() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get code =>
      (super.noSuchMethod(
            Invocation.getter(#code),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#code),
            ),
          )
          as String);
}

/// A class which mocks [PropertiesManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropertiesManager extends _i1.Mock implements _i22.PropertiesManager {
  MockPropertiesManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get clientSenderEmail =>
      (super.noSuchMethod(
            Invocation.getter(#clientSenderEmail),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#clientSenderEmail),
            ),
          )
          as String);

  @override
  String get revenueCatApiKey =>
      (super.noSuchMethod(
            Invocation.getter(#revenueCatApiKey),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#revenueCatApiKey),
            ),
          )
          as String);

  @override
  String get supportEmail =>
      (super.noSuchMethod(
            Invocation.getter(#supportEmail),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#supportEmail),
            ),
          )
          as String);

  @override
  String get sendGridApiKey =>
      (super.noSuchMethod(
            Invocation.getter(#sendGridApiKey),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#sendGridApiKey),
            ),
          )
          as String);

  @override
  String get feedbackTemplate =>
      (super.noSuchMethod(
            Invocation.getter(#feedbackTemplate),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#feedbackTemplate),
            ),
          )
          as String);

  @override
  _i14.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [PurchasesWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchasesWrapper extends _i1.Mock implements _i23.PurchasesWrapper {
  MockPurchasesWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<bool> get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  void addCustomerInfoUpdateListener(
    dynamic Function(_i5.CustomerInfo)? listener,
  ) => super.noSuchMethod(
    Invocation.method(#addCustomerInfoUpdateListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> configure(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#configure, [apiKey]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void setLogLevel(_i7.LogLevel? level) => super.noSuchMethod(
    Invocation.method(#setLogLevel, [level]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<_i5.Offerings> getOfferings() =>
      (super.noSuchMethod(
            Invocation.method(#getOfferings, []),
            returnValue: _i14.Future<_i5.Offerings>.value(
              _FakeOfferings_12(this, Invocation.method(#getOfferings, [])),
            ),
          )
          as _i14.Future<_i5.Offerings>);

  @override
  _i14.Future<_i5.CustomerInfo> getCustomerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerInfo, []),
            returnValue: _i14.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_6(
                this,
                Invocation.method(#getCustomerInfo, []),
              ),
            ),
          )
          as _i14.Future<_i5.CustomerInfo>);

  @override
  _i14.Future<_i7.LogInResult> logIn(String? appUserId) =>
      (super.noSuchMethod(
            Invocation.method(#logIn, [appUserId]),
            returnValue: _i14.Future<_i7.LogInResult>.value(
              _FakeLogInResult_13(this, Invocation.method(#logIn, [appUserId])),
            ),
          )
          as _i14.Future<_i7.LogInResult>);

  @override
  _i14.Future<_i5.CustomerInfo> purchasePackage(_i5.Package? package) =>
      (super.noSuchMethod(
            Invocation.method(#purchasePackage, [package]),
            returnValue: _i14.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_6(
                this,
                Invocation.method(#purchasePackage, [package]),
              ),
            ),
          )
          as _i14.Future<_i5.CustomerInfo>);

  @override
  _i14.Future<_i5.CustomerInfo> logOut() =>
      (super.noSuchMethod(
            Invocation.method(#logOut, []),
            returnValue: _i14.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_6(this, Invocation.method(#logOut, [])),
            ),
          )
          as _i14.Future<_i5.CustomerInfo>);

  @override
  _i14.Future<_i5.CustomerInfo> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i14.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_6(
                this,
                Invocation.method(#restorePurchases, []),
              ),
            ),
          )
          as _i14.Future<_i5.CustomerInfo>);
}

/// A class which mocks [StoreProduct].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreProduct extends _i1.Mock implements _i5.StoreProduct {
  MockStoreProduct() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  double get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0.0)
          as double);

  @override
  String get priceString =>
      (super.noSuchMethod(
            Invocation.getter(#priceString),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#priceString),
            ),
          )
          as String);

  @override
  String get currencyCode =>
      (super.noSuchMethod(
            Invocation.getter(#currencyCode),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#currencyCode),
            ),
          )
          as String);

  @override
  _i5.$StoreProductCopyWith<_i5.StoreProduct> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$StoreProductCopyWith_14<_i5.StoreProduct>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$StoreProductCopyWith<_i5.StoreProduct>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i24.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isFree =>
      (super.noSuchMethod(Invocation.getter(#isFree), returnValue: false)
          as bool);

  @override
  bool get isPro =>
      (super.noSuchMethod(Invocation.getter(#isPro), returnValue: false)
          as bool);

  @override
  _i14.Stream<void> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i14.Stream<void>.empty(),
          )
          as _i14.Stream<void>);

  @override
  _i14.Future<String> get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i14.Future<String>.value(
              _i12.dummyValue<String>(this, Invocation.getter(#userId)),
            ),
          )
          as _i14.Future<String>);

  @override
  _i14.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> purchaseSubscription(_i24.Subscription? sub) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseSubscription, [sub]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i24.RestoreSubscriptionResult> restoreSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSubscription, []),
            returnValue: _i14.Future<_i24.RestoreSubscriptionResult>.value(
              _i24.RestoreSubscriptionResult.noSubscriptionsFound,
            ),
          )
          as _i14.Future<_i24.RestoreSubscriptionResult>);

  @override
  _i14.Future<_i24.Subscriptions?> subscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#subscriptions, []),
            returnValue: _i14.Future<_i24.Subscriptions?>.value(),
          )
          as _i14.Future<_i24.Subscriptions?>);
}

/// A class which mocks [TimeManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeManager extends _i1.Mock implements _i9.TimeManager {
  MockTimeManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.TZDateTime get currentDateTime =>
      (super.noSuchMethod(
            Invocation.getter(#currentDateTime),
            returnValue: _FakeTZDateTime_15(
              this,
              Invocation.getter(#currentDateTime),
            ),
          )
          as _i8.TZDateTime);

  @override
  _i9.TimeZoneLocation get currentLocation =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocation),
            returnValue: _FakeTimeZoneLocation_16(
              this,
              Invocation.getter(#currentLocation),
            ),
          )
          as _i9.TimeZoneLocation);

  @override
  _i2.TimeOfDay get currentTime =>
      (super.noSuchMethod(
            Invocation.getter(#currentTime),
            returnValue: _FakeTimeOfDay_17(
              this,
              Invocation.getter(#currentTime),
            ),
          )
          as _i2.TimeOfDay);

  @override
  int get currentTimestamp =>
      (super.noSuchMethod(Invocation.getter(#currentTimestamp), returnValue: 0)
          as int);

  @override
  String get currentTimeZone =>
      (super.noSuchMethod(
            Invocation.getter(#currentTimeZone),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#currentTimeZone),
            ),
          )
          as String);

  @override
  _i14.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  List<_i9.TimeZoneLocation> filteredLocations(
    String? query, {
    _i9.TimeZoneLocation? exclude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filteredLocations, [query], {#exclude: exclude}),
            returnValue: <_i9.TimeZoneLocation>[],
          )
          as List<_i9.TimeZoneLocation>);

  @override
  _i8.TZDateTime dateTime(int? timestamp, [String? timeZone]) =>
      (super.noSuchMethod(
            Invocation.method(#dateTime, [timestamp, timeZone]),
            returnValue: _FakeTZDateTime_15(
              this,
              Invocation.method(#dateTime, [timestamp, timeZone]),
            ),
          )
          as _i8.TZDateTime);

  @override
  _i8.TZDateTime now([String? timeZone]) =>
      (super.noSuchMethod(
            Invocation.method(#now, [timeZone]),
            returnValue: _FakeTZDateTime_15(
              this,
              Invocation.method(#now, [timeZone]),
            ),
          )
          as _i8.TZDateTime);

  @override
  _i8.TZDateTime toTZDateTime(DateTime? dateTime) =>
      (super.noSuchMethod(
            Invocation.method(#toTZDateTime, [dateTime]),
            returnValue: _FakeTZDateTime_15(
              this,
              Invocation.method(#toTZDateTime, [dateTime]),
            ),
          )
          as _i8.TZDateTime);

  @override
  _i8.TZDateTime dateTimeFromSeconds(int? timestampSeconds) =>
      (super.noSuchMethod(
            Invocation.method(#dateTimeFromSeconds, [timestampSeconds]),
            returnValue: _FakeTZDateTime_15(
              this,
              Invocation.method(#dateTimeFromSeconds, [timestampSeconds]),
            ),
          )
          as _i8.TZDateTime);
}
