// Mocks generated by Mockito 5.4.6 from annotations
// in adair_flutter_lib/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i8;
import 'dart:ui' as _i3;

import 'package:adair_flutter_lib/adair_flutter_lib.dart' as _i15;
import 'package:adair_flutter_lib/app_config.dart' as _i16;
import 'package:adair_flutter_lib/managers/properties_manager.dart' as _i35;
import 'package:adair_flutter_lib/managers/subscription_manager.dart' as _i37;
import 'package:adair_flutter_lib/managers/time_manager.dart' as _i13;
import 'package:adair_flutter_lib/utils/log.dart' as _i31;
import 'package:adair_flutter_lib/wrappers/crashlytics_wrapper.dart' as _i18;
import 'package:adair_flutter_lib/wrappers/device_info_wrapper.dart' as _i20;
import 'package:adair_flutter_lib/wrappers/firebase_auth_wrapper.dart' as _i38;
import 'package:adair_flutter_lib/wrappers/io_wrapper.dart' as _i28;
import 'package:adair_flutter_lib/wrappers/local_notifications_wrapper.dart'
    as _i30;
import 'package:adair_flutter_lib/wrappers/native_time_zone_wrapper.dart'
    as _i32;
import 'package:adair_flutter_lib/wrappers/permission_handler_wrapper.dart'
    as _i33;
import 'package:adair_flutter_lib/wrappers/purchases_wrapper.dart' as _i36;
import 'package:device_info_plus/device_info_plus.dart' as _i6;
import 'package:firebase_auth/firebase_auth.dart' as _i14;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/services.dart' as _i34;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i9;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i23;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i25;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i26;
import 'package:flutter_local_notifications/src/types.dart' as _i27;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:purchases_flutter/models/entitlement_info_wrapper.dart' as _i7;
import 'package:purchases_flutter/models/entitlement_infos_wrapper.dart' as _i4;
import 'package:purchases_flutter/models/period_unit.dart' as _i29;
import 'package:purchases_flutter/models/store.dart' as _i21;
import 'package:purchases_flutter/models/store_transaction.dart' as _i19;
import 'package:purchases_flutter/models/verification_result.dart' as _i22;
import 'package:purchases_flutter/object_wrappers.dart' as _i5;
import 'package:purchases_flutter/purchases_flutter.dart' as _i11;
import 'package:timezone/timezone.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIconData_0 extends _i1.SmartFake implements _i2.IconData {
  _FakeIconData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMaterialColor_1 extends _i1.SmartFake implements _i2.MaterialColor {
  _FakeMaterialColor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeColor_2 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEntitlementInfos_3 extends _i1.SmartFake
    implements _i4.EntitlementInfos {
  _FakeEntitlementInfos_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CustomerInfoCopyWith_4<$Res> extends _i1.SmartFake
    implements _i5.$CustomerInfoCopyWith<$Res> {
  _Fake$CustomerInfoCopyWith_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidDeviceInfo_5 extends _i1.SmartFake
    implements _i6.AndroidDeviceInfo {
  _FakeAndroidDeviceInfo_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIosDeviceInfo_6 extends _i1.SmartFake implements _i6.IosDeviceInfo {
  _FakeIosDeviceInfo_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EntitlementInfoCopyWith_7<$Res> extends _i1.SmartFake
    implements _i7.$EntitlementInfoCopyWith<$Res> {
  _Fake$EntitlementInfoCopyWith_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EntitlementInfosCopyWith_8<$Res> extends _i1.SmartFake
    implements _i4.$EntitlementInfosCopyWith<$Res> {
  _Fake$EntitlementInfosCopyWith_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_9 extends _i1.SmartFake implements _i8.Directory {
  _FakeDirectory_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_10 extends _i1.SmartFake implements _i8.File {
  _FakeFile_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$IntroductoryPriceCopyWith_11<$Res> extends _i1.SmartFake
    implements _i5.$IntroductoryPriceCopyWith<$Res> {
  _Fake$IntroductoryPriceCopyWith_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterLocalNotificationsPlugin_12 extends _i1.SmartFake
    implements _i9.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeFuture_13<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomerInfo_14 extends _i1.SmartFake implements _i5.CustomerInfo {
  _FakeCustomerInfo_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OfferingCopyWith_15<$Res> extends _i1.SmartFake
    implements _i5.$OfferingCopyWith<$Res> {
  _Fake$OfferingCopyWith_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OfferingsCopyWith_16<$Res> extends _i1.SmartFake
    implements _i5.$OfferingsCopyWith<$Res> {
  _Fake$OfferingsCopyWith_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoreProduct_17 extends _i1.SmartFake implements _i5.StoreProduct {
  _FakeStoreProduct_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePresentedOfferingContext_18 extends _i1.SmartFake
    implements _i5.PresentedOfferingContext {
  _FakePresentedOfferingContext_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PackageCopyWith_19<$Res> extends _i1.SmartFake
    implements _i5.$PackageCopyWith<$Res> {
  _Fake$PackageCopyWith_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfferings_20 extends _i1.SmartFake implements _i5.Offerings {
  _FakeOfferings_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogInResult_21 extends _i1.SmartFake implements _i11.LogInResult {
  _FakeLogInResult_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StoreProductCopyWith_22<$Res> extends _i1.SmartFake
    implements _i5.$StoreProductCopyWith<$Res> {
  _Fake$StoreProductCopyWith_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTZDateTime_23 extends _i1.SmartFake implements _i12.TZDateTime {
  _FakeTZDateTime_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeZoneLocation_24 extends _i1.SmartFake
    implements _i13.TimeZoneLocation {
  _FakeTimeZoneLocation_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeOfDay_25 extends _i1.SmartFake implements _i2.TimeOfDay {
  _FakeTimeOfDay_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeZone_26 extends _i1.SmartFake implements _i12.TimeZone {
  _FakeTimeZone_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocation_27 extends _i1.SmartFake implements _i12.Location {
  _FakeLocation_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidBuildVersion_28 extends _i1.SmartFake
    implements _i6.AndroidBuildVersion {
  _FakeAndroidBuildVersion_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIosUtsname_29 extends _i1.SmartFake implements _i6.IosUtsname {
  _FakeIosUtsname_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_30 extends _i1.SmartFake
    implements _i14.UserCredential {
  _FakeUserCredential_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_31 extends _i1.SmartFake implements _i14.UserMetadata {
  _FakeUserMetadata_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_32 extends _i1.SmartFake implements _i14.MultiFactor {
  _FakeMultiFactor_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_33 extends _i1.SmartFake
    implements _i14.IdTokenResult {
  _FakeIdTokenResult_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_34 extends _i1.SmartFake
    implements _i14.ConfirmationResult {
  _FakeConfirmationResult_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_35 extends _i1.SmartFake implements _i14.User {
  _FakeUser_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdairFlutterLib].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdairFlutterLib extends _i1.Mock implements _i15.AdairFlutterLib {
  MockAdairFlutterLib() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [AppConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfig extends _i1.Mock implements _i16.AppConfig {
  MockAppConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String Function() get appName =>
      (super.noSuchMethod(
            Invocation.getter(#appName),
            returnValue: () =>
                _i17.dummyValue<String>(this, Invocation.getter(#appName)),
          )
          as String Function());

  @override
  _i2.IconData get appIcon =>
      (super.noSuchMethod(
            Invocation.getter(#appIcon),
            returnValue: _FakeIconData_0(this, Invocation.getter(#appIcon)),
          )
          as _i2.IconData);

  @override
  _i2.MaterialColor get colorAppTheme =>
      (super.noSuchMethod(
            Invocation.getter(#colorAppTheme),
            returnValue: _FakeMaterialColor_1(
              this,
              Invocation.getter(#colorAppTheme),
            ),
          )
          as _i2.MaterialColor);

  @override
  _i3.Color Function(bool) get colorAppBarContent =>
      (super.noSuchMethod(
            Invocation.getter(#colorAppBarContent),
            returnValue: (bool __p0) =>
                _FakeColor_2(this, Invocation.getter(#colorAppBarContent)),
          )
          as _i3.Color Function(bool));

  @override
  _i2.ThemeMode Function() get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: () => _i2.ThemeMode.system,
          )
          as _i2.ThemeMode Function());

  @override
  set appName(String Function()? value) => super.noSuchMethod(
    Invocation.setter(#appName, value),
    returnValueForMissingStub: null,
  );

  @override
  set appIcon(_i2.IconData? value) => super.noSuchMethod(
    Invocation.setter(#appIcon, value),
    returnValueForMissingStub: null,
  );

  @override
  set colorAppTheme(_i2.MaterialColor? value) => super.noSuchMethod(
    Invocation.setter(#colorAppTheme, value),
    returnValueForMissingStub: null,
  );

  @override
  set colorAppBarContent(_i3.Color Function(bool)? value) => super.noSuchMethod(
    Invocation.setter(#colorAppBarContent, value),
    returnValueForMissingStub: null,
  );

  @override
  set themeMode(_i2.ThemeMode Function()? value) => super.noSuchMethod(
    Invocation.setter(#themeMode, value),
    returnValueForMissingStub: null,
  );

  @override
  void init({
    required String Function()? appName,
    _i2.IconData? appIcon,
    _i2.MaterialColor? colorAppTheme,
    _i3.Color Function(bool)? colorAppBarContent,
    _i2.ThemeMode Function()? themeMode,
  }) => super.noSuchMethod(
    Invocation.method(#init, [], {
      #appName: appName,
      #appIcon: appIcon,
      #colorAppTheme: colorAppTheme,
      #colorAppBarContent: colorAppBarContent,
      #themeMode: themeMode,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CrashlyticsWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsWrapper extends _i1.Mock
    implements _i18.CrashlyticsWrapper {
  MockCrashlyticsWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> log(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#log, [message]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setUserId(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [identifier]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setCustomKey(String? key, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomKey, [key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> recordError(
    dynamic message,
    StackTrace? stack, {
    dynamic reason,
    Iterable<Object>? information = const [],
    bool? printDetails,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [message, stack],
              {
                #reason: reason,
                #information: information,
                #printDetails: printDetails,
                #fatal: fatal,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [CustomerInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerInfo extends _i1.Mock implements _i5.CustomerInfo {
  MockCustomerInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.EntitlementInfos get entitlements =>
      (super.noSuchMethod(
            Invocation.getter(#entitlements),
            returnValue: _FakeEntitlementInfos_3(
              this,
              Invocation.getter(#entitlements),
            ),
          )
          as _i4.EntitlementInfos);

  @override
  Map<String, String?> get allPurchaseDates =>
      (super.noSuchMethod(
            Invocation.getter(#allPurchaseDates),
            returnValue: <String, String?>{},
          )
          as Map<String, String?>);

  @override
  List<String> get activeSubscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get allPurchasedProductIdentifiers =>
      (super.noSuchMethod(
            Invocation.getter(#allPurchasedProductIdentifiers),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i19.StoreTransaction> get nonSubscriptionTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#nonSubscriptionTransactions),
            returnValue: <_i19.StoreTransaction>[],
          )
          as List<_i19.StoreTransaction>);

  @override
  String get firstSeen =>
      (super.noSuchMethod(
            Invocation.getter(#firstSeen),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#firstSeen),
            ),
          )
          as String);

  @override
  String get originalAppUserId =>
      (super.noSuchMethod(
            Invocation.getter(#originalAppUserId),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#originalAppUserId),
            ),
          )
          as String);

  @override
  Map<String, String?> get allExpirationDates =>
      (super.noSuchMethod(
            Invocation.getter(#allExpirationDates),
            returnValue: <String, String?>{},
          )
          as Map<String, String?>);

  @override
  String get requestDate =>
      (super.noSuchMethod(
            Invocation.getter(#requestDate),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#requestDate),
            ),
          )
          as String);

  @override
  _i5.$CustomerInfoCopyWith<_i5.CustomerInfo> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$CustomerInfoCopyWith_4<_i5.CustomerInfo>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$CustomerInfoCopyWith<_i5.CustomerInfo>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [DeviceInfoWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoWrapper extends _i1.Mock implements _i20.DeviceInfoWrapper {
  MockDeviceInfoWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i6.AndroidDeviceInfo> get androidInfo =>
      (super.noSuchMethod(
            Invocation.getter(#androidInfo),
            returnValue: _i10.Future<_i6.AndroidDeviceInfo>.value(
              _FakeAndroidDeviceInfo_5(this, Invocation.getter(#androidInfo)),
            ),
          )
          as _i10.Future<_i6.AndroidDeviceInfo>);

  @override
  _i10.Future<_i6.IosDeviceInfo> get iosInfo =>
      (super.noSuchMethod(
            Invocation.getter(#iosInfo),
            returnValue: _i10.Future<_i6.IosDeviceInfo>.value(
              _FakeIosDeviceInfo_6(this, Invocation.getter(#iosInfo)),
            ),
          )
          as _i10.Future<_i6.IosDeviceInfo>);
}

/// A class which mocks [EntitlementInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfo extends _i1.Mock implements _i7.EntitlementInfo {
  MockEntitlementInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  bool get isActive =>
      (super.noSuchMethod(Invocation.getter(#isActive), returnValue: false)
          as bool);

  @override
  bool get willRenew =>
      (super.noSuchMethod(Invocation.getter(#willRenew), returnValue: false)
          as bool);

  @override
  String get latestPurchaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#latestPurchaseDate),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#latestPurchaseDate),
            ),
          )
          as String);

  @override
  String get originalPurchaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#originalPurchaseDate),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#originalPurchaseDate),
            ),
          )
          as String);

  @override
  String get productIdentifier =>
      (super.noSuchMethod(
            Invocation.getter(#productIdentifier),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#productIdentifier),
            ),
          )
          as String);

  @override
  bool get isSandbox =>
      (super.noSuchMethod(Invocation.getter(#isSandbox), returnValue: false)
          as bool);

  @override
  _i7.OwnershipType get ownershipType =>
      (super.noSuchMethod(
            Invocation.getter(#ownershipType),
            returnValue: _i7.OwnershipType.purchased,
          )
          as _i7.OwnershipType);

  @override
  _i21.Store get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _i21.Store.appStore,
          )
          as _i21.Store);

  @override
  _i7.PeriodType get periodType =>
      (super.noSuchMethod(
            Invocation.getter(#periodType),
            returnValue: _i7.PeriodType.intro,
          )
          as _i7.PeriodType);

  @override
  _i22.VerificationResult get verification =>
      (super.noSuchMethod(
            Invocation.getter(#verification),
            returnValue: _i22.VerificationResult.notRequested,
          )
          as _i22.VerificationResult);

  @override
  _i7.$EntitlementInfoCopyWith<_i7.EntitlementInfo> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$EntitlementInfoCopyWith_7<_i7.EntitlementInfo>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i7.$EntitlementInfoCopyWith<_i7.EntitlementInfo>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [EntitlementInfos].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfos extends _i1.Mock implements _i4.EntitlementInfos {
  MockEntitlementInfos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i7.EntitlementInfo> get all =>
      (super.noSuchMethod(
            Invocation.getter(#all),
            returnValue: <String, _i7.EntitlementInfo>{},
          )
          as Map<String, _i7.EntitlementInfo>);

  @override
  Map<String, _i7.EntitlementInfo> get active =>
      (super.noSuchMethod(
            Invocation.getter(#active),
            returnValue: <String, _i7.EntitlementInfo>{},
          )
          as Map<String, _i7.EntitlementInfo>);

  @override
  _i22.VerificationResult get verification =>
      (super.noSuchMethod(
            Invocation.getter(#verification),
            returnValue: _i22.VerificationResult.notRequested,
          )
          as _i22.VerificationResult);

  @override
  _i4.$EntitlementInfosCopyWith<_i4.EntitlementInfos> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$EntitlementInfosCopyWith_8<_i4.EntitlementInfos>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i4.$EntitlementInfosCopyWith<_i4.EntitlementInfos>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i9.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool?> initialize(
    _i23.InitializationSettings? initializationSettings, {
    _i24.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i24.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [initializationSettings],
              {
                #onDidReceiveNotificationResponse:
                    onDidReceiveNotificationResponse,
                #onDidReceiveBackgroundNotificationResponse:
                    onDidReceiveBackgroundNotificationResponse,
              },
            ),
            returnValue: _i10.Future<bool?>.value(),
          )
          as _i10.Future<bool?>);

  @override
  _i10.Future<_i24.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue:
                _i10.Future<_i24.NotificationAppLaunchDetails?>.value(),
          )
          as _i10.Future<_i24.NotificationAppLaunchDetails?>);

  @override
  _i10.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i25.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [id, title, body, notificationDetails],
              {#payload: payload},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id], {#tag: tag}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAllPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllPendingNotifications, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i12.TZDateTime? scheduledDate,
    _i25.NotificationDetails? notificationDetails, {
    required _i26.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i27.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zonedSchedule,
              [id, title, body, scheduledDate, notificationDetails],
              {
                #androidScheduleMode: androidScheduleMode,
                #payload: payload,
                #matchDateTimeComponents: matchDateTimeComponents,
              },
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i24.RepeatInterval? repeatInterval,
    _i25.NotificationDetails? notificationDetails, {
    required _i26.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShow,
              [id, title, body, repeatInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i25.NotificationDetails? notificationDetails, {
    _i26.AndroidScheduleMode? androidScheduleMode =
        _i26.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShowWithDuration,
              [id, title, body, repeatDurationInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i24.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue:
                _i10.Future<List<_i24.PendingNotificationRequest>>.value(
                  <_i24.PendingNotificationRequest>[],
                ),
          )
          as _i10.Future<List<_i24.PendingNotificationRequest>>);

  @override
  _i10.Future<List<_i24.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i10.Future<List<_i24.ActiveNotification>>.value(
              <_i24.ActiveNotification>[],
            ),
          )
          as _i10.Future<List<_i24.ActiveNotification>>);
}

/// A class which mocks [IoWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIoWrapper extends _i1.Mock implements _i28.IoWrapper {
  MockIoWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAndroid =>
      (super.noSuchMethod(Invocation.getter(#isAndroid), returnValue: false)
          as bool);

  @override
  bool get isIOS =>
      (super.noSuchMethod(Invocation.getter(#isIOS), returnValue: false)
          as bool);

  @override
  bool get isWeb =>
      (super.noSuchMethod(Invocation.getter(#isWeb), returnValue: false)
          as bool);

  @override
  bool isFileSync(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isFileSync, [path]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Directory directory(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#directory, [path]),
            returnValue: _FakeDirectory_9(
              this,
              Invocation.method(#directory, [path]),
            ),
          )
          as _i8.Directory);

  @override
  _i8.File file(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#file, [path]),
            returnValue: _FakeFile_10(this, Invocation.method(#file, [path])),
          )
          as _i8.File);

  @override
  _i10.Future<List<_i8.InternetAddress>> lookup(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#lookup, [host]),
            returnValue: _i10.Future<List<_i8.InternetAddress>>.value(
              <_i8.InternetAddress>[],
            ),
          )
          as _i10.Future<List<_i8.InternetAddress>>);
}

/// A class which mocks [IntroductoryPrice].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntroductoryPrice extends _i1.Mock implements _i5.IntroductoryPrice {
  MockIntroductoryPrice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0.0)
          as double);

  @override
  String get priceString =>
      (super.noSuchMethod(
            Invocation.getter(#priceString),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#priceString),
            ),
          )
          as String);

  @override
  String get period =>
      (super.noSuchMethod(
            Invocation.getter(#period),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#period),
            ),
          )
          as String);

  @override
  int get cycles =>
      (super.noSuchMethod(Invocation.getter(#cycles), returnValue: 0) as int);

  @override
  _i29.PeriodUnit get periodUnit =>
      (super.noSuchMethod(
            Invocation.getter(#periodUnit),
            returnValue: _i29.PeriodUnit.day,
          )
          as _i29.PeriodUnit);

  @override
  int get periodNumberOfUnits =>
      (super.noSuchMethod(
            Invocation.getter(#periodNumberOfUnits),
            returnValue: 0,
          )
          as int);

  @override
  _i5.$IntroductoryPriceCopyWith<_i5.IntroductoryPrice> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue:
                _Fake$IntroductoryPriceCopyWith_11<_i5.IntroductoryPrice>(
                  this,
                  Invocation.getter(#copyWith),
                ),
          )
          as _i5.$IntroductoryPriceCopyWith<_i5.IntroductoryPrice>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [LocalNotificationsWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationsWrapper extends _i1.Mock
    implements _i30.LocalNotificationsWrapper {
  MockLocalNotificationsWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.FlutterLocalNotificationsPlugin newInstance() =>
      (super.noSuchMethod(
            Invocation.method(#newInstance, []),
            returnValue: _FakeFlutterLocalNotificationsPlugin_12(
              this,
              Invocation.method(#newInstance, []),
            ),
          )
          as _i9.FlutterLocalNotificationsPlugin);
}

/// A class which mocks [Log].
///
/// See the documentation for Mockito's code generation for more information.
class MockLog extends _i1.Mock implements _i31.Log {
  MockLog() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void d(String? msg) => super.noSuchMethod(
    Invocation.method(#d, [msg]),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    Object? exception, {
    String? reason,
    StackTrace? stackTrace,
    bool? fatal = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [exception],
      {#reason: reason, #stackTrace: stackTrace, #fatal: fatal},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(String? msg) => super.noSuchMethod(
    Invocation.method(#w, [msg]),
    returnValueForMissingStub: null,
  );

  @override
  T sync<T>(String? tag, int? msThreshold, T Function()? work) =>
      (super.noSuchMethod(
            Invocation.method(#sync, [tag, msThreshold, work]),
            returnValue: _i17.dummyValue<T>(
              this,
              Invocation.method(#sync, [tag, msThreshold, work]),
            ),
          )
          as T);

  @override
  _i10.Future<T> async<T>(
    String? tag,
    int? msThreshold,
    _i10.Future<T>? work,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#async, [tag, msThreshold, work]),
            returnValue:
                _i17.ifNotNull(
                  _i17.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#async, [tag, msThreshold, work]),
                  ),
                  (T v) => _i10.Future<T>.value(v),
                ) ??
                _FakeFuture_13<T>(
                  this,
                  Invocation.method(#async, [tag, msThreshold, work]),
                ),
          )
          as _i10.Future<T>);
}

/// A class which mocks [LogInResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogInResult extends _i1.Mock implements _i11.LogInResult {
  MockLogInResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get created =>
      (super.noSuchMethod(Invocation.getter(#created), returnValue: false)
          as bool);

  @override
  _i5.CustomerInfo get customerInfo =>
      (super.noSuchMethod(
            Invocation.getter(#customerInfo),
            returnValue: _FakeCustomerInfo_14(
              this,
              Invocation.getter(#customerInfo),
            ),
          )
          as _i5.CustomerInfo);
}

/// A class which mocks [NativeTimeZoneWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNativeTimeZoneWrapper extends _i1.Mock
    implements _i32.NativeTimeZoneWrapper {
  MockNativeTimeZoneWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<String>> getAvailableTimeZones() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableTimeZones, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<String> getLocalTimeZone() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalTimeZone, []),
            returnValue: _i10.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#getLocalTimeZone, []),
              ),
            ),
          )
          as _i10.Future<String>);
}

/// A class which mocks [Offering].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffering extends _i1.Mock implements _i5.Offering {
  MockOffering() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  String get serverDescription =>
      (super.noSuchMethod(
            Invocation.getter(#serverDescription),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#serverDescription),
            ),
          )
          as String);

  @override
  Map<String, Object> get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: <String, Object>{},
          )
          as Map<String, Object>);

  @override
  List<_i5.Package> get availablePackages =>
      (super.noSuchMethod(
            Invocation.getter(#availablePackages),
            returnValue: <_i5.Package>[],
          )
          as List<_i5.Package>);

  @override
  _i5.$OfferingCopyWith<_i5.Offering> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$OfferingCopyWith_15<_i5.Offering>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$OfferingCopyWith<_i5.Offering>);

  @override
  _i5.Package? getPackage(String? identifier) =>
      (super.noSuchMethod(Invocation.method(#getPackage, [identifier]))
          as _i5.Package?);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [Offerings].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfferings extends _i1.Mock implements _i5.Offerings {
  MockOfferings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i5.Offering> get all =>
      (super.noSuchMethod(
            Invocation.getter(#all),
            returnValue: <String, _i5.Offering>{},
          )
          as Map<String, _i5.Offering>);

  @override
  _i5.$OfferingsCopyWith<_i5.Offerings> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$OfferingsCopyWith_16<_i5.Offerings>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$OfferingsCopyWith<_i5.Offerings>);

  @override
  _i5.Offering? getOffering(String? identifier) =>
      (super.noSuchMethod(Invocation.method(#getOffering, [identifier]))
          as _i5.Offering?);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [Package].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackage extends _i1.Mock implements _i5.Package {
  MockPackage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  _i5.PackageType get packageType =>
      (super.noSuchMethod(
            Invocation.getter(#packageType),
            returnValue: _i5.PackageType.unknown,
          )
          as _i5.PackageType);

  @override
  _i5.StoreProduct get storeProduct =>
      (super.noSuchMethod(
            Invocation.getter(#storeProduct),
            returnValue: _FakeStoreProduct_17(
              this,
              Invocation.getter(#storeProduct),
            ),
          )
          as _i5.StoreProduct);

  @override
  _i5.PresentedOfferingContext get presentedOfferingContext =>
      (super.noSuchMethod(
            Invocation.getter(#presentedOfferingContext),
            returnValue: _FakePresentedOfferingContext_18(
              this,
              Invocation.getter(#presentedOfferingContext),
            ),
          )
          as _i5.PresentedOfferingContext);

  @override
  _i5.$PackageCopyWith<_i5.Package> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$PackageCopyWith_19<_i5.Package>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$PackageCopyWith<_i5.Package>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [PermissionHandlerWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionHandlerWrapper extends _i1.Mock
    implements _i33.PermissionHandlerWrapper {
  MockPermissionHandlerWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> get isLocationGranted =>
      (super.noSuchMethod(
            Invocation.getter(#isLocationGranted),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> get isLocationAlwaysGranted =>
      (super.noSuchMethod(
            Invocation.getter(#isLocationAlwaysGranted),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> get isNotificationDenied =>
      (super.noSuchMethod(
            Invocation.getter(#isNotificationDenied),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> get isNotificationGranted =>
      (super.noSuchMethod(
            Invocation.getter(#isNotificationGranted),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestLocation() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocation, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestLocationAlways() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationAlways, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestPhotos() =>
      (super.noSuchMethod(
            Invocation.method(#requestPhotos, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestNotification() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotification, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);
}

/// A class which mocks [PlatformException].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformException extends _i1.Mock implements _i34.PlatformException {
  MockPlatformException() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get code =>
      (super.noSuchMethod(
            Invocation.getter(#code),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#code),
            ),
          )
          as String);
}

/// A class which mocks [PropertiesManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropertiesManager extends _i1.Mock implements _i35.PropertiesManager {
  MockPropertiesManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get clientSenderEmail =>
      (super.noSuchMethod(
            Invocation.getter(#clientSenderEmail),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#clientSenderEmail),
            ),
          )
          as String);

  @override
  String get revenueCatGoogleApiKey =>
      (super.noSuchMethod(
            Invocation.getter(#revenueCatGoogleApiKey),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#revenueCatGoogleApiKey),
            ),
          )
          as String);

  @override
  String get revenueCatAppleApiKey =>
      (super.noSuchMethod(
            Invocation.getter(#revenueCatAppleApiKey),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#revenueCatAppleApiKey),
            ),
          )
          as String);

  @override
  String get supportEmail =>
      (super.noSuchMethod(
            Invocation.getter(#supportEmail),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#supportEmail),
            ),
          )
          as String);

  @override
  String get sendGridApiKey =>
      (super.noSuchMethod(
            Invocation.getter(#sendGridApiKey),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#sendGridApiKey),
            ),
          )
          as String);

  @override
  String get feedbackTemplate =>
      (super.noSuchMethod(
            Invocation.getter(#feedbackTemplate),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#feedbackTemplate),
            ),
          )
          as String);

  @override
  _i10.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  String stringForKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#stringForKey, [key]),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.method(#stringForKey, [key]),
            ),
          )
          as String);
}

/// A class which mocks [PurchasesWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchasesWrapper extends _i1.Mock implements _i36.PurchasesWrapper {
  MockPurchasesWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void addCustomerInfoUpdateListener(
    dynamic Function(_i5.CustomerInfo)? listener,
  ) => super.noSuchMethod(
    Invocation.method(#addCustomerInfoUpdateListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> configure(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#configure, [apiKey]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void setLogLevel(_i11.LogLevel? level) => super.noSuchMethod(
    Invocation.method(#setLogLevel, [level]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i5.Offerings> getOfferings() =>
      (super.noSuchMethod(
            Invocation.method(#getOfferings, []),
            returnValue: _i10.Future<_i5.Offerings>.value(
              _FakeOfferings_20(this, Invocation.method(#getOfferings, [])),
            ),
          )
          as _i10.Future<_i5.Offerings>);

  @override
  _i10.Future<_i5.CustomerInfo> getCustomerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerInfo, []),
            returnValue: _i10.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_14(
                this,
                Invocation.method(#getCustomerInfo, []),
              ),
            ),
          )
          as _i10.Future<_i5.CustomerInfo>);

  @override
  _i10.Future<_i11.LogInResult> logIn(String? appUserId) =>
      (super.noSuchMethod(
            Invocation.method(#logIn, [appUserId]),
            returnValue: _i10.Future<_i11.LogInResult>.value(
              _FakeLogInResult_21(this, Invocation.method(#logIn, [appUserId])),
            ),
          )
          as _i10.Future<_i11.LogInResult>);

  @override
  _i10.Future<_i5.CustomerInfo> purchasePackage(_i5.Package? package) =>
      (super.noSuchMethod(
            Invocation.method(#purchasePackage, [package]),
            returnValue: _i10.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_14(
                this,
                Invocation.method(#purchasePackage, [package]),
              ),
            ),
          )
          as _i10.Future<_i5.CustomerInfo>);

  @override
  _i10.Future<_i5.CustomerInfo> logOut() =>
      (super.noSuchMethod(
            Invocation.method(#logOut, []),
            returnValue: _i10.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_14(this, Invocation.method(#logOut, [])),
            ),
          )
          as _i10.Future<_i5.CustomerInfo>);

  @override
  _i10.Future<_i5.CustomerInfo> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i10.Future<_i5.CustomerInfo>.value(
              _FakeCustomerInfo_14(
                this,
                Invocation.method(#restorePurchases, []),
              ),
            ),
          )
          as _i10.Future<_i5.CustomerInfo>);
}

/// A class which mocks [StoreProduct].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreProduct extends _i1.Mock implements _i5.StoreProduct {
  MockStoreProduct() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier =>
      (super.noSuchMethod(
            Invocation.getter(#identifier),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#identifier),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  double get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0.0)
          as double);

  @override
  String get priceString =>
      (super.noSuchMethod(
            Invocation.getter(#priceString),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#priceString),
            ),
          )
          as String);

  @override
  String get currencyCode =>
      (super.noSuchMethod(
            Invocation.getter(#currencyCode),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#currencyCode),
            ),
          )
          as String);

  @override
  _i5.$StoreProductCopyWith<_i5.StoreProduct> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$StoreProductCopyWith_22<_i5.StoreProduct>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i5.$StoreProductCopyWith<_i5.StoreProduct>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i37.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isFree =>
      (super.noSuchMethod(Invocation.getter(#isFree), returnValue: false)
          as bool);

  @override
  bool get isPro =>
      (super.noSuchMethod(Invocation.getter(#isPro), returnValue: false)
          as bool);

  @override
  _i10.Stream<void> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<void>.empty(),
          )
          as _i10.Stream<void>);

  @override
  _i10.Future<String> get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i10.Future<String>.value(
              _i17.dummyValue<String>(this, Invocation.getter(#userId)),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> purchaseSubscription(_i37.Subscription? sub) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseSubscription, [sub]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i37.RestoreSubscriptionResult> restoreSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSubscription, []),
            returnValue: _i10.Future<_i37.RestoreSubscriptionResult>.value(
              _i37.RestoreSubscriptionResult.noSubscriptionsFound,
            ),
          )
          as _i10.Future<_i37.RestoreSubscriptionResult>);

  @override
  _i10.Future<_i37.Subscriptions?> subscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#subscriptions, []),
            returnValue: _i10.Future<_i37.Subscriptions?>.value(),
          )
          as _i10.Future<_i37.Subscriptions?>);
}

/// A class which mocks [TimeManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeManager extends _i1.Mock implements _i13.TimeManager {
  MockTimeManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.TZDateTime get currentDateTime =>
      (super.noSuchMethod(
            Invocation.getter(#currentDateTime),
            returnValue: _FakeTZDateTime_23(
              this,
              Invocation.getter(#currentDateTime),
            ),
          )
          as _i12.TZDateTime);

  @override
  _i13.TimeZoneLocation get currentLocation =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocation),
            returnValue: _FakeTimeZoneLocation_24(
              this,
              Invocation.getter(#currentLocation),
            ),
          )
          as _i13.TimeZoneLocation);

  @override
  _i2.TimeOfDay get currentTime =>
      (super.noSuchMethod(
            Invocation.getter(#currentTime),
            returnValue: _FakeTimeOfDay_25(
              this,
              Invocation.getter(#currentTime),
            ),
          )
          as _i2.TimeOfDay);

  @override
  int get currentTimestamp =>
      (super.noSuchMethod(Invocation.getter(#currentTimestamp), returnValue: 0)
          as int);

  @override
  String get currentTimeZone =>
      (super.noSuchMethod(
            Invocation.getter(#currentTimeZone),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#currentTimeZone),
            ),
          )
          as String);

  @override
  _i10.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  List<_i13.TimeZoneLocation> filteredLocations(
    String? query, {
    _i13.TimeZoneLocation? exclude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filteredLocations, [query], {#exclude: exclude}),
            returnValue: <_i13.TimeZoneLocation>[],
          )
          as List<_i13.TimeZoneLocation>);

  @override
  _i12.TZDateTime dateTime(int? timestamp, [String? timeZone]) =>
      (super.noSuchMethod(
            Invocation.method(#dateTime, [timestamp, timeZone]),
            returnValue: _FakeTZDateTime_23(
              this,
              Invocation.method(#dateTime, [timestamp, timeZone]),
            ),
          )
          as _i12.TZDateTime);

  @override
  _i12.TZDateTime dateTimeFromSeconds(
    int? timestampSeconds, [
    String? timeZone,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#dateTimeFromSeconds, [
              timestampSeconds,
              timeZone,
            ]),
            returnValue: _FakeTZDateTime_23(
              this,
              Invocation.method(#dateTimeFromSeconds, [
                timestampSeconds,
                timeZone,
              ]),
            ),
          )
          as _i12.TZDateTime);

  @override
  _i12.TZDateTime dateTimeFromValues(
    int? year, [
    int? month = 1,
    int? day = 1,
    int? hour = 0,
    int? minute = 0,
    int? second = 0,
    int? millisecond = 0,
    int? microsecond = 0,
    String? timeZone,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#dateTimeFromValues, [
              year,
              month,
              day,
              hour,
              minute,
              second,
              millisecond,
              microsecond,
              timeZone,
            ]),
            returnValue: _FakeTZDateTime_23(
              this,
              Invocation.method(#dateTimeFromValues, [
                year,
                month,
                day,
                hour,
                minute,
                second,
                millisecond,
                microsecond,
                timeZone,
              ]),
            ),
          )
          as _i12.TZDateTime);

  @override
  _i12.TZDateTime dateTimeToTz(DateTime? dateTime) =>
      (super.noSuchMethod(
            Invocation.method(#dateTimeToTz, [dateTime]),
            returnValue: _FakeTZDateTime_23(
              this,
              Invocation.method(#dateTimeToTz, [dateTime]),
            ),
          )
          as _i12.TZDateTime);

  @override
  _i12.TZDateTime now([String? timeZone]) =>
      (super.noSuchMethod(
            Invocation.method(#now, [timeZone]),
            returnValue: _FakeTZDateTime_23(
              this,
              Invocation.method(#now, [timeZone]),
            ),
          )
          as _i12.TZDateTime);
}

/// A class which mocks [TimeZoneLocation].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockTimeZoneLocation extends _i1.Mock implements _i13.TimeZoneLocation {
  MockTimeZoneLocation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.TimeZone get currentTimeZone =>
      (super.noSuchMethod(
            Invocation.getter(#currentTimeZone),
            returnValue: _FakeTimeZone_26(
              this,
              Invocation.getter(#currentTimeZone),
            ),
          )
          as _i12.TimeZone);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  String get displayNameUtc =>
      (super.noSuchMethod(
            Invocation.getter(#displayNameUtc),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#displayNameUtc),
            ),
          )
          as String);

  @override
  String get displayUtc =>
      (super.noSuchMethod(
            Invocation.getter(#displayUtc),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#displayUtc),
            ),
          )
          as String);

  @override
  _i12.Location get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeLocation_27(this, Invocation.getter(#value)),
          )
          as _i12.Location);

  @override
  bool matchesFilter(String? filter) =>
      (super.noSuchMethod(
            Invocation.method(#matchesFilter, [filter]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [AndroidBuildVersion].
///
/// See the documentation for Mockito's code generation for more information.
class MockAndroidBuildVersion extends _i1.Mock
    implements _i6.AndroidBuildVersion {
  MockAndroidBuildVersion() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get codename =>
      (super.noSuchMethod(
            Invocation.getter(#codename),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#codename),
            ),
          )
          as String);

  @override
  String get incremental =>
      (super.noSuchMethod(
            Invocation.getter(#incremental),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#incremental),
            ),
          )
          as String);

  @override
  String get release =>
      (super.noSuchMethod(
            Invocation.getter(#release),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#release),
            ),
          )
          as String);

  @override
  int get sdkInt =>
      (super.noSuchMethod(Invocation.getter(#sdkInt), returnValue: 0) as int);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [AndroidDeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAndroidDeviceInfo extends _i1.Mock implements _i6.AndroidDeviceInfo {
  MockAndroidDeviceInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AndroidBuildVersion get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _FakeAndroidBuildVersion_28(
              this,
              Invocation.getter(#version),
            ),
          )
          as _i6.AndroidBuildVersion);

  @override
  String get board =>
      (super.noSuchMethod(
            Invocation.getter(#board),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#board),
            ),
          )
          as String);

  @override
  String get bootloader =>
      (super.noSuchMethod(
            Invocation.getter(#bootloader),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#bootloader),
            ),
          )
          as String);

  @override
  String get brand =>
      (super.noSuchMethod(
            Invocation.getter(#brand),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#brand),
            ),
          )
          as String);

  @override
  String get device =>
      (super.noSuchMethod(
            Invocation.getter(#device),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#device),
            ),
          )
          as String);

  @override
  String get display =>
      (super.noSuchMethod(
            Invocation.getter(#display),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#display),
            ),
          )
          as String);

  @override
  String get fingerprint =>
      (super.noSuchMethod(
            Invocation.getter(#fingerprint),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#fingerprint),
            ),
          )
          as String);

  @override
  String get hardware =>
      (super.noSuchMethod(
            Invocation.getter(#hardware),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#hardware),
            ),
          )
          as String);

  @override
  String get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#host),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i17.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get manufacturer =>
      (super.noSuchMethod(
            Invocation.getter(#manufacturer),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#manufacturer),
            ),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#model),
            ),
          )
          as String);

  @override
  String get product =>
      (super.noSuchMethod(
            Invocation.getter(#product),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#product),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  List<String> get supported32BitAbis =>
      (super.noSuchMethod(
            Invocation.getter(#supported32BitAbis),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get supported64BitAbis =>
      (super.noSuchMethod(
            Invocation.getter(#supported64BitAbis),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get supportedAbis =>
      (super.noSuchMethod(
            Invocation.getter(#supportedAbis),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  String get tags =>
      (super.noSuchMethod(
            Invocation.getter(#tags),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#tags),
            ),
          )
          as String);

  @override
  String get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#type),
            ),
          )
          as String);

  @override
  bool get isPhysicalDevice =>
      (super.noSuchMethod(
            Invocation.getter(#isPhysicalDevice),
            returnValue: false,
          )
          as bool);

  @override
  int get freeDiskSize =>
      (super.noSuchMethod(Invocation.getter(#freeDiskSize), returnValue: 0)
          as int);

  @override
  int get totalDiskSize =>
      (super.noSuchMethod(Invocation.getter(#totalDiskSize), returnValue: 0)
          as int);

  @override
  List<String> get systemFeatures =>
      (super.noSuchMethod(
            Invocation.getter(#systemFeatures),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  String get serialNumber =>
      (super.noSuchMethod(
            Invocation.getter(#serialNumber),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#serialNumber),
            ),
          )
          as String);

  @override
  bool get isLowRamDevice =>
      (super.noSuchMethod(
            Invocation.getter(#isLowRamDevice),
            returnValue: false,
          )
          as bool);

  @override
  int get physicalRamSize =>
      (super.noSuchMethod(Invocation.getter(#physicalRamSize), returnValue: 0)
          as int);

  @override
  int get availableRamSize =>
      (super.noSuchMethod(Invocation.getter(#availableRamSize), returnValue: 0)
          as int);

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [IosDeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIosDeviceInfo extends _i1.Mock implements _i6.IosDeviceInfo {
  MockIosDeviceInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get systemName =>
      (super.noSuchMethod(
            Invocation.getter(#systemName),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#systemName),
            ),
          )
          as String);

  @override
  String get systemVersion =>
      (super.noSuchMethod(
            Invocation.getter(#systemVersion),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#systemVersion),
            ),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#model),
            ),
          )
          as String);

  @override
  String get modelName =>
      (super.noSuchMethod(
            Invocation.getter(#modelName),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#modelName),
            ),
          )
          as String);

  @override
  String get localizedModel =>
      (super.noSuchMethod(
            Invocation.getter(#localizedModel),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#localizedModel),
            ),
          )
          as String);

  @override
  bool get isPhysicalDevice =>
      (super.noSuchMethod(
            Invocation.getter(#isPhysicalDevice),
            returnValue: false,
          )
          as bool);

  @override
  int get physicalRamSize =>
      (super.noSuchMethod(Invocation.getter(#physicalRamSize), returnValue: 0)
          as int);

  @override
  int get availableRamSize =>
      (super.noSuchMethod(Invocation.getter(#availableRamSize), returnValue: 0)
          as int);

  @override
  bool get isiOSAppOnMac =>
      (super.noSuchMethod(Invocation.getter(#isiOSAppOnMac), returnValue: false)
          as bool);

  @override
  _i6.IosUtsname get utsname =>
      (super.noSuchMethod(
            Invocation.getter(#utsname),
            returnValue: _FakeIosUtsname_29(this, Invocation.getter(#utsname)),
          )
          as _i6.IosUtsname);

  @override
  int get freeDiskSize =>
      (super.noSuchMethod(Invocation.getter(#freeDiskSize), returnValue: 0)
          as int);

  @override
  int get totalDiskSize =>
      (super.noSuchMethod(Invocation.getter(#totalDiskSize), returnValue: 0)
          as int);

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [FirebaseAuthWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthWrapper extends _i1.Mock
    implements _i38.FirebaseAuthWrapper {
  MockFirebaseAuthWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i14.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i10.Stream<_i14.User?>.empty(),
          )
          as _i10.Stream<_i14.User?>);

  @override
  _i10.Stream<_i14.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i10.Stream<_i14.User?>.empty(),
          )
          as _i10.Stream<_i14.User?>);

  @override
  _i10.Future<_i14.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i14.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i14.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_31(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i14.UserMetadata);

  @override
  List<_i14.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i14.UserInfo>[],
          )
          as List<_i14.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i17.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i14.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_32(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i14.MultiFactor);

  @override
  _i10.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<_i14.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i10.Future<_i14.IdTokenResult>.value(
              _FakeIdTokenResult_33(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i10.Future<_i14.IdTokenResult>);

  @override
  _i10.Future<_i14.UserCredential> linkWithCredential(
    _i14.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<_i14.UserCredential> linkWithProvider(
    _i14.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<_i14.UserCredential> reauthenticateWithProvider(
    _i14.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<_i14.UserCredential> reauthenticateWithPopup(
    _i14.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<void> reauthenticateWithRedirect(_i14.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i14.UserCredential> linkWithPopup(_i14.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<void> linkWithRedirect(_i14.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i14.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i14.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i10.Future<_i14.ConfirmationResult>.value(
              _FakeConfirmationResult_34(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i10.Future<_i14.ConfirmationResult>);

  @override
  _i10.Future<_i14.UserCredential> reauthenticateWithCredential(
    _i14.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i10.Future<_i14.UserCredential>.value(
              _FakeUserCredential_30(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i10.Future<_i14.UserCredential>);

  @override
  _i10.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> sendEmailVerification([
    _i14.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i14.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i10.Future<_i14.User>.value(
              _FakeUser_35(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i10.Future<_i14.User>);

  @override
  _i10.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updatePhoneNumber(
    _i14.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i14.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i14.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}
